version: '3.3'

services:
  trono:
    build: ./builds/gui
    ports:
      - "3000:22"
      - "5900:5900"
      - "6080:80"
    container_name: trono    
    hostname: trono
    privileged: true
    volumes:
        - ./trono/nftables-trono.conf:/etc/nftables.conf
        - ./trono/engade-ruta.bash:/engade-ruta.bash
        - ./trono/index-trono.html:/usr/local/lib/web/frontend/index.html
    networks:
      default:
      redit:
        ipv4_address: 192.168.30.3
  it01:
    build: ./builds/gui
    container_name: it01    
    hostname: it01
    privileged: true
    volumes:
        - ./it01/nftables-it01.conf:/etc/nftables.conf
        - ./it01/engade-ruta.bash:/engade-ruta.bash
    networks:
      redit:
        ipv4_address: 192.168.30.21
  rrhh01:
    build: ./builds/gui
    container_name: rrhh01    
    hostname: rrhh01
    privileged: true
    volumes:
        - ./rrhh01/nftables-rrhh01.conf:/etc/nftables.conf
        - ./rrhh01/engade-ruta.bash:/engade-ruta.bash
    networks:
      redrrhh:
        ipv4_address: 192.168.20.21
  com01:
    build: ./builds/gui
    container_name: com01    
    hostname: com01
    privileged: true
    volumes:
        - ./com01/nftables-com01.conf:/etc/nftables.conf
        - ./com01/engade-ruta.bash:/engade-ruta.bash
    networks:
      redcom:
        ipv4_address: 192.168.10.21
  printerrrhh:
    build: ./builds/ssh-apache
    container_name: printerrrhh    
    hostname: printerrrhh
    privileged: true
    volumes:
        - ./printerrrhh/index-printerrrhh.html:/var/www/html/index.html
        - ./printerrrhh/nftables-printerrrhh.conf:/etc/nftables.conf
        - ./printerrrhh/engade-ruta.bash:/engade-ruta.bash
    networks:
      redrrhh:
        ipv4_address: 192.168.20.50
  printercom:
    build: ./builds/ssh-apache
    container_name: printerrrhh    
    hostname: printerrrhh
    privileged: true
    volumes:
        - ./printercom/index-printercom.html:/var/www/html/index.html
        - ./printercom/nftables-printercom.conf:/etc/nftables.conf
        - ./printercom/engade-ruta.bash:/engade-ruta.bash
    networks:
      redcom:
        ipv4_address: 192.168.10.50
  firewallint:
    build: ./builds/ssh
    container_name: firewallint   
    hostname: firewallint
    privileged: true
    volumes:
        - ./firewallint/nftables-firewallint.conf:/etc/nftables.conf
        - ./firewallint/engade-ruta.bash:/engade-ruta.bash
    networks:
      redit:
        ipv4_address: 192.168.30.1
      redrrhh:
        ipv4_address: 192.168.20.1
      redcom:
        ipv4_address: 192.168.10.1
      redinterna:
        ipv4_address: 192.168.0.2
  firewallfrontera:
    build: ./builds/ssh
    container_name: firewallfrontera   
    hostname: firewallfrontera
    privileged: true
    volumes:
        - ./firewallfrontera/nftables-firewallfrontera.conf:/etc/nftables.conf
        - ./firewallfrontera/engade-ruta.bash:/engade-ruta.bash
    networks:
      dmz:
        ipv4_address: 192.168.40.1
      redpublica:
        ipv4_address: 45.60.60.60
      redinterna:
        ipv4_address: 192.168.0.1
  webserver:
    build: ./builds/ssh-apache
    container_name: webserver  
    hostname: webserver
    privileged: true
    volumes:
        - ./server/nftables-server.conf:/etc/nftables.conf
        - ./server/index-web.html:/usr/local/lib/web/frontend/index.html
        - ./server/engade-ruta.bash:/engade-ruta.bash
    networks:
      dmz:
        ipv4_address: 192.168.40.10
  emailserver:
    build: ./builds/ssh-apache
    container_name: emailserver  
    hostname: emailserver
    privileged: true
    volumes:
        - ./server/nftables-server.conf:/etc/nftables.conf
        - ./server/index-email.html:/usr/local/lib/web/frontend/index.html
        - ./server/engade-ruta.bash:/engade-ruta.bash
    networks:
      dmz:
        ipv4_address: 192.168.40.20
  internetserver:
    build: ./builds/ssh-apache
    container_name: webserver  
    hostname: webserver
    privileged: true
    volumes:
        - ./internetserver/nftables-server.conf:/etc/nftables.conf
        - ./internetserver/index-internet.html:/usr/local/lib/web/frontend/index.html
        - ./internetserver/engade-ruta.bash:/engade-ruta.bash
    networks:
      redpublica:
        ipv4_address: 45.60.60.45
networks:
  redcom:
    internal: true #Bloquea o acceso a internet
    ipam:
      config:
        - subnet: 192.168.10.0/24 
  redrrhh:
    internal: true #Bloquea o acceso a internet
    ipam:
      config:
        - subnet: 192.168.20.0/24
  redit:
    internal: true #Bloquea o acceso a internet
    ipam:
      config:
        - subnet: 192.168.30.0/24
  dmz:
    internal: true #Bloquea o acceso a internet
    ipam:
      config:
        - subnet: 192.168.40.0/24
  redinterna:
    internal: true #Bloquea o acceso a internet
    ipam:
      config:
        - subnet: 192.168.0.0/30
  redpublica:
    driver: bridge
    ipam:
      config:
        - subnet: 45.60.60.0/24 
